// Generated by scripts/export_web_icons.py. Edit assets/icons masters.

type IconProps = { x: number; y: number; height: number; fill: string };

function Icon_turn_l({ x, y, height, fill }: IconProps) {
  const width = height * 1.53125;
  return <svg x={x - width / 2} y={y - height / 2} width={width} height={height}
    viewBox="7.5 8 49 32" aria-hidden>{/* shared silhouette */}
    <path fill={fill} d="M42.6 8.4 8.2 24l34.4 15.6v-8.2H56V16.6H42.6z"/>
  </svg>;
}

function Icon_turn_r({ x, y, height, fill }: IconProps) {
  const width = height * 1.5076923076923077;
  return <svg x={x - width / 2} y={y - height / 2} width={width} height={height}
    viewBox="7.5 8 49 32.5" aria-hidden>{/* shared silhouette */}
    <path fill={fill} d="M21.4 8.4v8.2H8v15.2h13.4v8.2L55.8 24z"/>
  </svg>;
}

function Icon_high_beam({ x, y, height, fill }: IconProps) {
  const width = height * 1.7;
  return <svg x={x - width / 2} y={y - height / 2} width={width} height={height}
    viewBox="2.5 7 59.5 34" aria-hidden>{/* shared silhouette */}
    <g fill={fill}>
    <rect x="3.4" y="12.4" width="22.8" height="3.5" rx="0.35"/>
    <rect x="3.4" y="22.25" width="22.8" height="3.5" rx="0.35"/>
    <rect x="3.4" y="32.1" width="22.8" height="3.5" rx="0.35"/>
    <path fillRule="evenodd" d="M32.6 7.6h6.2C54.4 7.6 61.2 14.6 61.2 24S54.4 40.4 38.8 40.4h-6.2V7.6z M36.8 12.2v23.6h2.8c11.6 0 16.4-5.5 16.4-11.8S51.2 12.2 39.6 12.2h-2.8z"/>
  </g>
  </svg>;
}

function Icon_battery({ x, y, height, fill }: IconProps) {
  const width = height * 1.175;
  return <svg x={x - width / 2} y={y - height / 2} width={width} height={height}
    viewBox="8.5 4 47 40" aria-hidden>{/* shared silhouette */}
    <g fill={fill}>
    <rect x="18.2" y="4.6" width="9.6" height="7" rx="0.7"/>
    <rect x="36.2" y="4.6" width="9.6" height="7" rx="0.7"/>
    <path fillRule="evenodd" d="M9.2 12.2h45.6v31.2H9.2z M14.4 17.4h35.2v20.8H14.4z"/>
    <rect x="18.8" y="25.4" width="10.8" height="3.1"/>
    <rect x="22.65" y="21.55" width="3.1" height="10.8"/>
    <rect x="34.6" y="25.4" width="10.8" height="3.1"/>
  </g>
  </svg>;
}

function Icon_oil({ x, y, height, fill }: IconProps) {
  const width = height * 1.7;
  return <svg x={x - width / 2} y={y - height / 2} width={width} height={height}
    viewBox="2 10 60.5 27.5" aria-hidden>{/* shared silhouette */}
    <g fill="none" stroke={fill} strokeWidth="3" strokeLinejoin="round">
<path d="M17 19h23l13-7 3 4-14 17H18L10 21H4v-6h10z"/>
<path d="M24 19v-6m-6 0h13"/>
</g><path fill={fill} d="M58 24c-2 4-4 6-4 9a4 4 0 0 0 8 0c0-3-2-5-4-9z"/>
  </svg>;
}

function Icon_cel({ x, y, height, fill }: IconProps) {
  const width = height * 1.7;
  return <svg x={x - width / 2} y={y - height / 2} width={width} height={height}
    viewBox="2 8 60.5 30" aria-hidden>{/* shared silhouette */}
    <g fill={fill}>
    <path fillRule="evenodd" d="M16.4 8.8h19.2c1.7 0 3.15 1.05 3.7 2.6l1.85 5.2h8.4l4.4-4.7h4.8v6.4h3.1v12.4h-3.1v6.6H8.2v-6.6H2.6V25.8h5.2v-4h6.8L15 11.4c.5-1.55 1.95-2.6 3.4-2.6z M16.2 22.2h5.1v2.05h-3.05v4.5h3.05v2.05h-5.1zM22.2 22.2h2.05v3.35h1.7V22.2h2.05v8.6h-2.05v-3.2h-1.7v3.2H22.2zM29.1 22.2h5.05v2.05h-3v1.55h2.45v1.9H31.15v1.05h3v2.05h-5.05zM35.3 22.2h5.1v2.05h-3.05v4.5h3.05v2.05h-5.1zM41.5 22.2h2.1v3.15l2.55-3.15h2.35L45.3 26.4l3.35 4.4h-2.45l-2.05-2.7v2.7h-2.1z"/>
  </g>
  </svg>;
}

function Icon_immobilizer({ x, y, height, fill }: IconProps) {
  const width = height * 1.7;
  return <svg x={x - width / 2} y={y - height / 2} width={width} height={height}
    viewBox="0.5 4.5 63.5 36.5" aria-hidden>{/* shared silhouette */}
    <g fill={fill}>
    <path fillRule="evenodd" d="M17.6 5.2a16.6 16.6 0 1 0 .02 0zm0 7.2a9.4 9.4 0 1 0 .02 0z"/>
    <rect x="30.6" y="19.4" width="30.2" height="7.8" rx="1.4"/>
    <rect x="45.6" y="27" width="4.8" height="7.4" rx="0.7"/>
    <rect x="52.2" y="27" width="4.8" height="10.2" rx="0.7"/>
    <rect x="58.8" y="27" width="4.8" height="13.2" rx="0.7"/>
  </g>
  </svg>;
}

function Icon_seatbelt({ x, y, height, fill }: IconProps) {
  const width = height * 0.6853932584269663;
  return <svg x={x - width / 2} y={y - height / 2} width={width} height={height}
    viewBox="17.5 1 30.5 44.5" aria-hidden>{/* shared silhouette */}
    <g fill={fill}>
    <circle cx="32" cy="7.8" r="6.2"/>
    <path d="M29.4 13.4h5.2v3.2h-5.2z"/>
    <path fillRule="evenodd" d="M18.2 18.2 25.8 16.4 29.2 19.4h5.6l3.4-3 7.6 1.8-2.4 26.6H20.6z M21.6 15.4 47.4 45h-8.8L20.2 22.2z"/>
  </g>
  </svg>;
}

function Icon_door({ x, y, height, fill }: IconProps) {
  const width = height * 1.3333333333333333;
  return <svg x={x - width / 2} y={y - height / 2} width={width} height={height}
    viewBox="2 1.5 60 45" aria-hidden>{/* shared silhouette */}
    <g fill={fill}>
    <path fillRule="evenodd" d="M24.8 2.4h14.4c2.05 0 3.9 1.15 4.8 3L48 11.8v25.8c0 1.75-1.05 3.35-2.7 4.35L38.4 46H25.6l-6.9-4.05c-1.65-1-2.7-2.6-2.7-4.35V11.8L20 5.4c.9-1.85 2.75-3 4.8-3z M27.4 8.4h9.2v8.8h-9.2z"/>
    <path d="M18.2 20.6 2.8 28.6l3.4 5.8 13.4-7.1z"/>
    <path d="M45.8 20.6 61.2 28.6l-3.4 5.8-13.4-7.1z"/>
  </g>
  </svg>;
}

function Icon_airbag({ x, y, height, fill }: IconProps) {
  const width = height * 1.0;
  return <svg x={x - width / 2} y={y - height / 2} width={width} height={height}
    viewBox="9.5 2.5 43 43" aria-hidden>{/* shared silhouette */}
    <g fill={fill}><circle cx="21" cy="8" r="5"/><circle cx="43" cy="22" r="9"/>
<path d="M17 15h8l5 13-5 4-6-10-3 11h15l6 12h-7l-5-7H10z"/></g>
  </svg>;
}

function Icon_coolant({ x, y, height, fill }: IconProps) {
  const width = height * 0.8;
  return <svg x={x - width / 2} y={y - height / 2} width={width} height={height}
    viewBox="11 3 36 45" aria-hidden>{/* shared silhouette */}
    <g fill="none" stroke={fill} strokeWidth="2.6" strokeLinecap="round"><path d="M27 27V5h6v22a6 6 0 1 1-6 0zM34 9h7m-7 7h7m-7 7h7M13 38q4-4 8 0t8 0 8 0 8 0M13 44q4-4 8 0t8 0 8 0 8 0"/></g>
  </svg>;
}

function Icon_fuel({ x, y, height, fill }: IconProps) {
  const width = height * 1.2236842105263157;
  return <svg x={x - width / 2} y={y - height / 2} width={width} height={height}
    viewBox="8.5 5 46.5 38" aria-hidden>{/* shared silhouette */}
    <g fill="none" stroke={fill} strokeWidth="3" strokeLinejoin="round"><path d="M14 41V7h22v34M9 41h32M36 19h5v15q0 7 6 7t6-7V17L43 7M45 9v10h8"/><path d="M19 12h12v10H19z"/></g>
  </svg>;
}

function Icon_trunk({ x, y, height, fill }: IconProps) {
  const width = height * 1.7;
  return <svg x={x - width / 2} y={y - height / 2} width={width} height={height}
    viewBox="2.5 10.5 57 33" aria-hidden>{/* shared silhouette */}
    <g fill={fill}><path d="M5 27h8l10-10h20l10 10h6v10H5z"/><circle cx="17" cy="38" r="5"/><circle cx="48" cy="38" r="5"/><path d="m7 23-4-11 3-1 6 12z"/></g>
  </svg>;
}

export const PICTOGRAMS = {
  turn_l: Icon_turn_l,
  turn_r: Icon_turn_r,
  high_beam: Icon_high_beam,
  battery: Icon_battery,
  oil: Icon_oil,
  cel: Icon_cel,
  immobilizer: Icon_immobilizer,
  seatbelt: Icon_seatbelt,
  door: Icon_door,
  airbag: Icon_airbag,
  coolant: Icon_coolant,
  fuel: Icon_fuel,
  trunk: Icon_trunk,
} as const;
