"""Generate React pictograms from the same SVG/PNG masters as pygame.

The alpha crop matches oem_icons._trim_alpha, so `height` means the visible
silhouette in both renderers, not transparent padding around a drawing.
Run after write_icon_svgs.py and rasterize_icons.py. --check is read-only.
"""
from pathlib import Path
import re
import sys
import xml.etree.ElementTree as ET

import pygame

ROOT = Path(__file__).resolve().parents[1]
KINDS = ("turn_l", "turn_r", "high_beam", "battery", "oil", "cel",
         "immobilizer", "seatbelt", "door", "airbag", "coolant", "fuel", "trunk")


def generate() -> str:
    parts = ['// Generated by scripts/export_web_icons.py. Edit assets/icons masters.\n',
             'type IconProps = { x: number; y: number; height: number; fill: string };\n']
    for kind in KINDS:
        root = ET.parse(ROOT / f"assets/icons/{kind}.svg").getroot()
        vb = list(map(float, root.attrib["viewBox"].split()))
        png = pygame.image.load(str(ROOT / f"assets/icons/{kind}.png"))
        box = png.get_bounding_rect(min_alpha=17).inflate(2, 2).clip(png.get_rect())
        x, y = box.x * vb[2] / png.get_width(), box.y * vb[3] / png.get_height()
        w, h = box.w * vb[2] / png.get_width(), box.h * vb[3] / png.get_height()
        raw = (ROOT / f"assets/icons/{kind}.svg").read_text()
        body = raw[raw.index('>', raw.index('<svg')) + 1:raw.rindex('</svg>')]
        body = re.sub(r'<!--.*?-->|<title>.*?</title>', '', body, flags=re.S)
        body = body.replace('"#fff"', '{fill}').replace('"#ffffff"', '{fill}')
        for attr in ('fill-rule', 'stroke-width', 'stroke-linecap', 'stroke-linejoin', 'clip-rule'):
            body = body.replace(attr, re.sub(r'-([a-z])', lambda m: m[1].upper(), attr))
        ratio = min(w / h, 1.7)
        parts.append(f'''function Icon_{kind}({{ x, y, height, fill }}: IconProps) {{
  const width = height * {ratio!r};
  return <svg x={{x - width / 2}} y={{y - height / 2}} width={{width}} height={{height}}
    viewBox="{x:g} {y:g} {w:g} {h:g}" aria-hidden>{{/* shared silhouette */}}
    {body.strip()}
  </svg>;
}}
''')
    parts.append('export const PICTOGRAMS = {\n' + ''.join(f'  {k}: Icon_{k},\n' for k in KINDS) + '} as const;\n')
    return '\n'.join(parts)


if __name__ == '__main__':
    target = ROOT / 'apps/harness/components/LampIcons.tsx'
    content = generate()
    if '--check' in sys.argv:
        if target.read_text() != content:
            sys.exit('Web icons stale: run uv run python scripts/export_web_icons.py')
    else:
        target.write_text(content)
