// =============================================================================
// Dimensions — Option 1 replace-face stack (arc lock)
// =============================================================================
// Face geometry comes from face_lock.scad, generated by src/face_spec.py from
// the same numbers that drive pygame and the web harness. Edit the Python
// spec, re-run `uv run python src/face_spec.py`, never this file's lock values.
//
// Millimetre sizes are ESTIMATED (170 × 72.3, 2.35:1 from
// refs/flat/DIMENSIONS.md). Callipers are UNKNOWN. Every stack thickness is a
// PLACEHOLDER. This is NOT a verified AP1 drop-in.
//
// Origin (OpenSCAD): bottom-left of the module bounding box, Z toward driver.
// The lock uses top-left fractions — convert with X() / Y() / W() / H().
// =============================================================================

include <face_lock.scad>

$fn = 64;
eps = 0.08;

// --- module envelope (ESTIMATED mm) -----------------------------------------
face_w = 170.0;                     // ESTIMATED — TODO measure OEM face width
face_h = face_w / module_aspect;    // 72.3 — TODO measure height

// --- fraction → mm helpers ---------------------------------------------------
function W(f) = f * face_w;                  // width fraction → mm
function H(f) = f * face_h;                  // height fraction → mm
function X(f) = f * face_w;                  // x from the left
function Y(f) = face_h - f * face_h;         // y measured from the TOP → y-up
function Yw(yw) = face_h - yw * face_w;      // width-unit y (arc maths) → y-up
function h_to_w(f) = f / module_aspect;      // height fraction → width units
function rect_mm(r) = [X(r[0]), Y(r[1] + r[3]), W(r[2]), H(r[3])];   // [x, y, w, h] y-up
function pt_mm(a) = [X(a[0]), Y(a[1])];

// Tach / crown circles in mm (y-up). Angles stay screen-space in the lock
// (0° = +x, positive = clockwise on screen) → negate for y-up.
tach_c = [W(tach_cx), Yw(h_to_w(tach_cy_h))];
crown_c = [W(tach_cx), Yw(h_to_w(crown_cy_h))];
function on_circle(c, r_mm, deg_screen) = [c[0] + r_mm * cos(-deg_screen), c[1] + r_mm * sin(-deg_screen)];
function tach_pt(r_frac, deg) = on_circle(tach_c, W(r_frac), deg);
function crown_pt(r_frac, deg) = on_circle(crown_c, W(r_frac), deg);

spring_y = Y(spring_y_h);
// Where the crown circle (radius r, width units) meets the spring line — half-chord in mm.
function crown_half(r_frac) =
    let (dy = crown_c[1] - spring_y)
    sqrt(max(0, W(r_frac) * W(r_frac) - dy * dy));

arc_steps = 72;

// Display windows in the mask, as margins around the lock geometry (mm).
tach_win_margin = 1.2;              // beyond r_out / inside r_num, and past the hatches
tach_win_num_depth = W(0.030);      // window reaches this far inside the numeral radius
min_rim = 1.8;                      // mask rim kept around every window
lcd_win_r = 1.0;                    // corner radius on the LCD windows
gauge_pad = 1.6;                    // TEMP / FUEL window grows to include icon + letters
strip_pad = 0.8;
arc_lamp_hole_clear = 0.25;

// --- 7" panel pocket (Wisecoco-class 16:9 AMOLED; PLACEHOLDER) ---------------
// Active area is centred on the module. It is TALLER than the face (87 > 72.3)
// and NARROWER (154 < 170): every display window sits inside it, the hardware
// buttons at both ends sit over the panel's dead border. Verify against the
// real panel drawing before printing — every number here is a guess.
panel_w = 164.0;                    // PLACEHOLDER module outline
panel_h = 100.0;
panel_t = 2.6;                      // PLACEHOLDER glass + PCB + stiffener
panel_active_w = 154.0;             // PLACEHOLDER
panel_active_h = 87.0;
panel_clear = 0.3;                  // slip around the module
panel_c = [face_w / 2, face_h / 2];
panel_tail_w = 30.0;                // FPC exit — LOCATION UNKNOWN (bottom centre guess)
panel_tail_h = 3.0;

// --- stack thicknesses (ALL PLACEHOLDER / TODO measure) ---------------------
face_t = 2.0;                       // acrylic / printed mask
tray_h = 12.0;                      // overall tray
floor_t = 1.6;                      // tray floor
wall = 2.0;                         // tray wall
face_pocket_clear = 0.35;           // slip around the dropped-in face
diffuser_t = 0.0;                   // AMOLED — no diffuser sheet in this stack
cable_w = 16.0;                     // driver-board cable escape — LOCATION UNKNOWN
cable_h = 4.0;

align_hole_d = 2.3;                 // PLACEHOLDER — do not drill the bay from this

button_clear = 0.40;                // PLACEHOLDER hole oversize
button_cap_t = 2.4;                 // proud cap
button_flange_t = 1.2;              // retention flange
button_flange_extra = 1.6;          // radial flange beyond cap
rocker_groove_w = 0.80;
rocker_groove_d = 1.10;
stem_well_d = 6.0;                  // switch well in the tray — switch UNKNOWN
stem_well_h = 7.0;

// --- derived -----------------------------------------------------------------
web_t = 1.0;                        // baffle web between panel glass and mask
face_rebate_z = tray_h - face_t;
panel_z = face_rebate_z - panel_t - web_t;   // panel glass sits under the web
panel_rect = [panel_c[0] - panel_w / 2, panel_c[1] - panel_h / 2, panel_w, panel_h];
active_rect = [panel_c[0] - panel_active_w / 2, panel_c[1] - panel_active_h / 2, panel_active_w, panel_active_h];

btn_d_mm = W(btn_d);
btn_minus_c = pt_mm(btn_minus);
btn_plus_c = pt_mm(btn_plus);
btn_sel_c = pt_mm(btn_sel);
btn_trip_c = pt_mm(btn_trip);
oval_w_mm = W(oval_w);
oval_h_mm = H(oval_h);
rocker_w = btn_plus_c[0] - btn_minus_c[0] + btn_d_mm;   // −/+ pair as one rocker cap
rocker_h = btn_d_mm;
